### ISSUE TITLE
React Loading Page

### ISSUE THREAD

**Issue by rafaeltedesco** [rafaeltedesco/azure-storage-file-system-full-stack#1]
Create a loading component. When sending files to the backend, the application does not provide an indication that it is working.

**Comment by Pratham271** [comment]
I can fix this

**Comment by rafaeltedesco** [comment]
> I can fix this

It would be great if you could contribute!

**Comment by Pratham271** [comment]
Hi there, 
I have added a state management to create loading on the load button like this 
 <button 
        disabled={isDisabled()} 
        className={`button-1 ${isDisabled() ? "disabled" : "active"}`} 
        onClick={submit}>
          {isLoading ? "Loading..." : "Load"}
        </button>
        Now I just want to know do you want this or a complete spinner

**Comment by Pratham271** [comment]
In my opinion loader would be better but I am confused that where will it look better on the home page or side panel where the images are shown.

**Comment by rafaeltedesco** [comment]
> In my opinion loader would be better but I am confused that where will it look better on the home page or side panel where the images are shown.

Great! I agree with you that it would be better. You've also raised a good point about where we could place the element. I hadn't thought about that until now, and I'm in doubt as well. Perhaps on the home page, we could consider replacing the text 'drag'n drop,' given that people might still think it's possible to drop images there. What do you think?

**Comment by Pratham271** [comment]
> Great! I agree with you that it would be better. You've also raised a good point about where we could place the element. I hadn't thought about that until now, and I'm in doubt as well. Perhaps on the home page, we could consider replacing the text 'drag'n drop,' given that people might still think it's possible to drop images there. What do you think?

I will use useContext to make the loader on both home and side panel and whichever looks better, we will use that one because the added images will be displayed on the side panel and I am thinking the loader will be more meaningful there, but as mentioned earlier confusion is still there.

**Comment by rafaeltedesco** [comment]
> > Great! I agree with you that it would be better. You've also raised a good point about where we could place the element. I hadn't thought about that until now, and I'm in doubt as well. Perhaps on the home page, we could consider replacing the text 'drag'n drop,' given that people might still think it's possible to drop images there. What do you think?
> 
> I will use useContext to make the loader on both home and side panel and whichever looks better, we will use that one because the added images will be displayed on the side panel and I am thinking the loader will be more meaningful there, but as mentioned earlier confusion is still there.

That's right, it makes sense. The loader on the side panel might be more meaningful.

**Comment by Pratham271** [comment]
Hi there, I raised a pr few days ago. So please check it whenever you get time

**Comment by Pratham271** [comment]
Hi there, I raised the pr after making all the changes just wanted to know if it is according to your needs and whether you will merge it or not

**Comment by rafaeltedesco** [comment]
Hello! Pr merged! Thank you so much for your help!

**Comment by Pratham271** [comment]
Your welcome
